package com.zzy.mapper;

import com.zzy.model.dto.BuildDTO;
import com.zzy.model.po.VdBuild;
import com.zzy.model.vo.BuildVO;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface VdBuildMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_build
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_build
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    int insert(VdBuild record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_build
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    VdBuild selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_build
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    List<VdBuild> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_build
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    int updateByPrimaryKey(VdBuild record);

    List<BuildDTO> selectByCondition(BuildVO vo);
    List<BuildDTO> buildSelect(BuildVO vo);
}