package com.zzy.mapper;

import com.zzy.model.po.VdCls;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface VdClsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_cls
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_cls
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    int insert(VdCls record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_cls
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    VdCls selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_cls
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    List<VdCls> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_cls
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    int updateByPrimaryKey(VdCls record);
}