package com.zzy.mapper;

import com.zzy.model.dto.ClassDTO;
import com.zzy.model.po.VdCls;
import com.zzy.model.vo.ClassVO;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface VdClsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_cls
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_cls
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    int insert(ClassVO vo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_cls
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    VdCls selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_cls
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    List<ClassDTO> selectAll(ClassVO vo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_cls
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    int updateByPrimaryKey(ClassVO vo);
}