package com.zzy.mapper;

import com.zzy.model.dto.DorDTO;
import com.zzy.model.po.VdDor;
import com.zzy.model.vo.DorVO;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface VdDorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_dor
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    int deleteByPrimaryKey(Integer id);
    int deleteByBid(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_dor
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    int insert(DorVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_dor
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    VdDor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_dor
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    List<VdDor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_dor
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    int updateByPrimaryKey(DorVO record);

    List<DorDTO> selectAllDormitory(DorVO vo);
    List<DorDTO> selectIsEmpty(DorVO vo);
}