package com.zzy.mapper;

import com.zzy.model.dto.LosAndFixDTO;
import com.zzy.model.po.VdFix;
import com.zzy.model.vo.LosAndFixVO;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface VdFixMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_fix
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_fix
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    int insert(LosAndFixVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_fix
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    List<LosAndFixDTO> selectAll(LosAndFixVO vo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_fix
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    int updateByPrimaryKey(LosAndFixVO record);
}