package com.zzy.mapper;

import com.zzy.model.po.VdLos;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface VdLosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_los
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_los
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    int insert(VdLos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_los
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    VdLos selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_los
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    List<VdLos> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_los
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    int updateByPrimaryKey(VdLos record);
}