package com.zzy.mapper;

import com.zzy.model.po.VdRole;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface VdRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_role
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_role
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    int insert(VdRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_role
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    VdRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_role
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    List<VdRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_role
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    int updateByPrimaryKey(VdRole record);
}