package com.zzy.mapper;

import com.zzy.model.po.VdStudentFix;
import com.zzy.model.po.VdStudentFixExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface VdStudentFixMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_student_fix
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    long countByExample(VdStudentFixExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_student_fix
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    int deleteByExample(VdStudentFixExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_student_fix
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_student_fix
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    int insert(VdStudentFix record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_student_fix
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    int insertSelective(VdStudentFix record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_student_fix
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    List<VdStudentFix> selectByExample(VdStudentFixExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_student_fix
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    VdStudentFix selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_student_fix
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    int updateByExampleSelective(@Param("record") VdStudentFix record, @Param("example") VdStudentFixExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_student_fix
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    int updateByExample(@Param("record") VdStudentFix record, @Param("example") VdStudentFixExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_student_fix
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    int updateByPrimaryKeySelective(VdStudentFix record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vd_student_fix
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    int updateByPrimaryKey(VdStudentFix record);
}
