package com.zzy.model.po;

import lombok.Data;

@Data
public class VdBuild {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_build.id
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_build.name
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    private String name;
    private String no;

    public String getNo() {
        return no;
    }

    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_build.id
     *
     * @return the value of vd_build.id
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_build.id
     *
     * @param id the value for vd_build.id
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_build.name
     *
     * @return the value of vd_build.name
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_build.name
     *
     * @param name the value for vd_build.name
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}
