package com.zzy.model.po;
import lombok.Data;

@Data
public class VdCls {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_cls.id
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_cls.name
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_cls.flag
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_cls.id
     *
     * @return the value of vd_cls.id
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_cls.id
     *
     * @param id the value for vd_cls.id
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_cls.name
     *
     * @return the value of vd_cls.name
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_cls.name
     *
     * @param name the value for vd_cls.name
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_cls.flag
     *
     * @return the value of vd_cls.flag
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_cls.flag
     *
     * @param flag the value for vd_cls.flag
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}