package com.zzy.model.po;

import lombok.Data;

@Data
public class VdDor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_dor.id
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_dor.bid
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    private Integer bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_dor.floor
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    private Integer floor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_dor.num
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_dor.dornum
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    private Integer dornum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_dor.maxnum
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    private Integer maxnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_dor.heal
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    private Integer heal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_dor.id
     *
     * @return the value of vd_dor.id
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_dor.id
     *
     * @param id the value for vd_dor.id
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_dor.bid
     *
     * @return the value of vd_dor.bid
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_dor.bid
     *
     * @param bid the value for vd_dor.bid
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_dor.floor
     *
     * @return the value of vd_dor.floor
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public Integer getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_dor.floor
     *
     * @param floor the value for vd_dor.floor
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public void setFloor(Integer floor) {
        this.floor = floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_dor.num
     *
     * @return the value of vd_dor.num
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_dor.num
     *
     * @param num the value for vd_dor.num
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public void setNum(String num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_dor.dornum
     *
     * @return the value of vd_dor.dornum
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public Integer getDornum() {
        return dornum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_dor.dornum
     *
     * @param dornum the value for vd_dor.dornum
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public void setDornum(Integer dornum) {
        this.dornum = dornum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_dor.maxnum
     *
     * @return the value of vd_dor.maxnum
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public Integer getMaxnum() {
        return maxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_dor.maxnum
     *
     * @param maxnum the value for vd_dor.maxnum
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public void setMaxnum(Integer maxnum) {
        this.maxnum = maxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_dor.heal
     *
     * @return the value of vd_dor.heal
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public Integer getHeal() {
        return heal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_dor.heal
     *
     * @param heal the value for vd_dor.heal
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public void setHeal(Integer heal) {
        this.heal = heal;
    }
}
