package com.zzy.model.po;

import lombok.Data;

@Data
public class VdLos {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_los.id
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_los.name
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_los.content
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_los.flag
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_los.id
     *
     * @return the value of vd_los.id
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_los.id
     *
     * @param id the value for vd_los.id
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_los.name
     *
     * @return the value of vd_los.name
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_los.name
     *
     * @param name the value for vd_los.name
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_los.content
     *
     * @return the value of vd_los.content
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_los.content
     *
     * @param content the value for vd_los.content
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_los.flag
     *
     * @return the value of vd_los.flag
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_los.flag
     *
     * @param flag the value for vd_los.flag
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}
