package com.zzy.model.po;

public class VdStudentFix {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_student_fix.id
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_student_fix.stuff
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    private String stuff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_student_fix.desc
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_student_fix.cover
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    private String cover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_student_fix.dorid
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    private Integer dorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_student_fix.process
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    private Integer process;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_student_fix.display
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    private Integer display;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_student_fix.id
     *
     * @return the value of vd_student_fix.id
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_student_fix.id
     *
     * @param id the value for vd_student_fix.id
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_student_fix.stuff
     *
     * @return the value of vd_student_fix.stuff
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    public String getStuff() {
        return stuff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_student_fix.stuff
     *
     * @param stuff the value for vd_student_fix.stuff
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    public void setStuff(String stuff) {
        this.stuff = stuff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_student_fix.desc
     *
     * @return the value of vd_student_fix.desc
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_student_fix.desc
     *
     * @param desc the value for vd_student_fix.desc
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_student_fix.cover
     *
     * @return the value of vd_student_fix.cover
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_student_fix.cover
     *
     * @param cover the value for vd_student_fix.cover
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    public void setCover(String cover) {
        this.cover = cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_student_fix.dorid
     *
     * @return the value of vd_student_fix.dorid
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    public Integer getDorid() {
        return dorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_student_fix.dorid
     *
     * @param dorid the value for vd_student_fix.dorid
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    public void setDorid(Integer dorid) {
        this.dorid = dorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_student_fix.process
     *
     * @return the value of vd_student_fix.process
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    public Integer getProcess() {
        return process;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_student_fix.process
     *
     * @param process the value for vd_student_fix.process
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    public void setProcess(Integer process) {
        this.process = process;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_student_fix.display
     *
     * @return the value of vd_student_fix.display
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    public Integer getDisplay() {
        return display;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_student_fix.display
     *
     * @param display the value for vd_student_fix.display
     *
     * @mbg.generated Tue Mar 02 21:07:51 CST 2021
     */
    public void setDisplay(Integer display) {
        this.display = display;
    }
}