package com.zzy.model.po;
import lombok.Data;

@Data
public class VdStu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_stu.id
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_stu.num
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_stu.name
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_stu.password
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_stu.sex
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_stu.clsid
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    private Integer clsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_stu.dorid
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    private Integer dorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vd_stu.flag
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_stu.id
     *
     * @return the value of vd_stu.id
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_stu.id
     *
     * @param id the value for vd_stu.id
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_stu.num
     *
     * @return the value of vd_stu.num
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_stu.num
     *
     * @param num the value for vd_stu.num
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public void setNum(String num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_stu.name
     *
     * @return the value of vd_stu.name
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_stu.name
     *
     * @param name the value for vd_stu.name
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_stu.password
     *
     * @return the value of vd_stu.password
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_stu.password
     *
     * @param password the value for vd_stu.password
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_stu.sex
     *
     * @return the value of vd_stu.sex
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_stu.sex
     *
     * @param sex the value for vd_stu.sex
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_stu.clsid
     *
     * @return the value of vd_stu.clsid
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public Integer getClsid() {
        return clsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_stu.clsid
     *
     * @param clsid the value for vd_stu.clsid
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public void setClsid(Integer clsid) {
        this.clsid = clsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_stu.dorid
     *
     * @return the value of vd_stu.dorid
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public Integer getDorid() {
        return dorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_stu.dorid
     *
     * @param dorid the value for vd_stu.dorid
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public void setDorid(Integer dorid) {
        this.dorid = dorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vd_stu.flag
     *
     * @return the value of vd_stu.flag
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vd_stu.flag
     *
     * @param flag the value for vd_stu.flag
     *
     * @mbg.generated Wed Jan 08 14:27:59 CST 2020
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}